name: AoC CI (Lint & Test)

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "1.18.0", "1.19.0", "1.20.0", "1.21.0", "stable" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.version}}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...